### ISSUE TITLE
Can't execute simple example

### ISSUE THREAD

**Issue by alexsb** [MSeal/agglom_cluster#10]
Thanks for this package! I'm trying to run the clustering as stated in the example. I'm on Python 3 on Mac, in a Jupyter Notebook on an Anaconda installation. I've installed agglom_cluster with pip, as instructed. When I run:
```python
from hac import GreedyAgglomerativeClusterer
clusterer = GreedyAgglomerativeClusterer()
# This cluster call is where most of the heavy lifting happens
dendrogram = clusterer.cluster(nx.karate_club_graph())
```

I get:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-8ff22bc75d9e> in <module>()
      2 clusterer = GreedyAgglomerativeClusterer()
      3 # This cluster call is where most of the heavy lifting happens
----> 4 dendrogram = clusterer.cluster(nx.karate_club_graph())
      5 dendrogram.clusters(1)
      6 

/Users/alexsb/anaconda/lib/python3.5/site-packages/hac/cluster.pyx in hac.cluster.GreedyAgglomerativeClusterer.cluster (hac/cluster.c:3297)()

TypeError: Expected list, got map
```
Is this a bug or is something wrong with my installation? Thx.

**Comment by MSeal** [comment]
Sorry for the delayed response -- I hadn't looked at my older repositories for a bit.

The issue is likely with running on Python3, I think there needs to be a pass done to fixup any Python3 issues and add a travis build for both environments. If you run in Python2.7 it should be fine.

**Comment by VersionBeathon** [comment]
@alexsb So am I

**Comment by MSeal** [comment]
Release 2.0.2 now supports python 3.2-3.7 as well as 2.7.

**Comment by VersionBeathon** [comment]
@MSeal Thank you

**Comment by alexsb** [comment]
Thanks!
