### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jcmontx** [MSeal/agglom_cluster#13]
I wanted to install the package through conda but it's only available for linux64, any chance to make it compatible with win64?

**Comment by MSeal** [comment]
It should support Windows already, I've used to instructions on the README to use it locally on my windows environment for a few years. Can you specify what steps you took that resulted in a failed installation?

**Comment by MSeal** [comment]
Perhaps you need to take steps outlined here: https://stackoverflow.com/questions/29286624/how-to-install-pypi-packages-using-anacaonda-conda-command ?
