### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by parashardhapola** [MSeal/agglom_cluster#15]
Hi,

I using Python 3.6 and the example fails with following error:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-29-658ee935be60> in <module>()
          2 clusterer = GreedyAgglomerativeClusterer()
          3 # This cluster call is where most of the heavy lifting happens
    ----> 4 karate_dendrogram = clusterer.cluster(nx.karate_club_graph())

    hac\cluster.pyx in hac.cluster.GreedyAgglomerativeClusterer.cluster (hac/cluster.c:4563)()

    hac\cluster.pyx in hac.cluster.int_graph_mapping (hac/cluster.c:3185)()

    AttributeError: 'Graph' object has no attribute 'nodes_iter'

I ran the following code:

    import networkx as nx
    from hac import GreedyAgglomerativeClusterer
    clusterer = GreedyAgglomerativeClusterer()
    karate_dendrogram = clusterer.cluster(nx.karate_club_graph())

**Comment by MSeal** [comment]
The v2.0.6 release now support networkx 1 or 2 (which makes the error you see go away).
