### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by parashardhapola** [MSeal/agglom_cluster#16]
Hi

I'm facing an unusual error while running the greedy cluster:

Source:

    import networkx as nx
    import hac
    G = nx.read_edgelist('hac_test_edgelist.tsv')
    clusterer = hac.GreedyAgglomerativeClusterer()
    agglomDendrogram = clusterer.cluster(G)

I get following error:

    ---------------------------------------------------------------------------
    RuntimeError                              Traceback (most recent call last)
    <ipython-input-3-37e7920a517a> in <module>()
          4 G = nx.read_edgelist('hac_test_edgelist.tsv')
          5 clusterer = hac.GreedyAgglomerativeClusterer()
    ----> 6 agglomDendrogram = clusterer.cluster(G)
    
    ~/anaconda3/lib/python3.6/site-packages/hac/cluster.pyx in hac.cluster.GreedyAgglomerativeClusterer.cluster()
    
    ~/anaconda3/lib/python3.6/site-packages/hac/cluster.pyx in hac.cluster.GreedyAgglomerativeClusterer.run_greedy_clustering()

    RuntimeError: dictionary changed size during iteration

The edgelist file can be downloaded from [here](https://tinyurl.com/y78ojxx9)
I'm unable to figure out why this specific edgelist is causes this error. I had created this edgelist from a networkx graph and is read by networkx without any errors.

**Comment by parashardhapola** [comment]
This particular graph has two disjoint sub graphs and I think this is the cause of error.

**Comment by MSeal** [comment]
I would imagine it would have difficulties with disjoint sub-graphs. We handle orphans with a sweep for isolated independent nodes but the work it was doing would never form disjoint sub-graphs so I can't directly account for it. It should additionally run a [connected subgraph query](https://networkx.github.io/documentation/networkx-1.9.1/reference/generated/networkx.algorithms.components.connected.connected_component_subgraphs.html) and run clustering on each subgraph. I probably can't get to making this change for a bit, but if you wanted to contribute, that change wouldn't be too hard to add.

**Comment by wenquanli** [comment]
I also meet this error while running the greedy cluster on some dataset.I carefully studied the dataset and discovered that some nodes were isolated from others in the graph, such as twenty-sixth node in the netscience.gml. Maybe this is the cause of the mistake.

**Comment by parashardhapola** [comment]
I will close this issue as this is not a problem with the algorithm itself.
For other reaching here from Google: please make sure your graph is not disjoint or has isolated nodes before running the clustering.
